---
permalink: intro-family.html 
keywords: introduction, what is ONTAP systems, AFF, FAS, ASA, all-flash, ONTAP 
summary: Die NetApp ONTAP Storage-Systeme sind speziell für Enterprise-Applikationen konzipiert, die leicht zu managenden, schnellen und sicheren Storage mit Zuverlässigkeit der Enterprise-Klasse und kontinuierlichem Datenzugriff benötigen. 
---
= Weitere Informationen zu ONTAP Hardware-Systemen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Die ONTAP Hardwaresysteme von NetApp wurden für Enterprise-Applikationen konzipiert, die leicht zu managenden, schnellen und sicheren Storage mit Zuverlässigkeit der Enterprise-Klasse und kontinuierlichem Datenzugriff benötigen.

Die ONTAP Hardwaresysteme von NetApp sind in All-Flash- (AFF) und Hybrid-Flash- und rein HDD-basierten Konfigurationen (FAS) erhältlich. Somit haben Sie die Möglichkeit, die Storage-Medienmischung auszuwählen, die Ihren Performance-, Kapazitäts- und Kostenanforderungen am besten entspricht.

Sie können verschiedene Modellkombinationen in Clustern zusammenführen, um gemischte Workloads auf demselben Storage-System auszuführen und Ihre Umgebung mit den neuesten Technologien um neue Storage-Generationen zu erweitern.



== All-Flash FAS Systeme (AFF)

NVMe-basierte AFF Systeme sind eine robuste horizontal skalierbare Plattform, die speziell für virtualisierte Umgebungen entwickelt wurde und als unabhängiges System oder hochperformantes Tier in einer NetApp ONTAP Konfiguration implementiert werden kann.

Die rein Flash-basierten FAS Konfigurationen unterstützen eine Vielzahl von Workloads, insbesondere VDI und Datenbanken, die hohe Performance, niedrige Latenz und Zuverlässigkeit erfordern, und sind somit die ideale Wahl für geschäftskritische Applikationen.

* https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["Lesen Sie das Datenblatt zur AFF A-Serie"^]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["Lesen Sie das Datenblatt zur AFF C-Serie"^]




== All-Flash SAN-Array-Systeme (ASA

NetApp All-Flash SAN-Arrays (ASA) sorgen für ein vereinfachtes, dediziertes SAN-Arbeitsumfeld mit kontinuierlicher Verfügbarkeit für geschäftskritische Enterprise-Datenbanken und sonstige SAN-Workloads über FCP oder iSCSI.

.ASA r2-Systeme
Die neuen NetApp ASA r2 Systeme (ASA A1K, ASA A70 und ASA A90) bieten eine einheitliche Hardware- und Softwarelösung, mit der die Benutzerfreundlichkeit speziell auf die Anforderungen reiner SAN-Kunden abgestimmt wird.

Auf einem ASA r2 System sorgen ONTAP und System Manager für den Support wichtiger SAN-Funktionen. Gleichzeitig sind die Funktionen und Funktionen, die in SAN-Umgebungen nicht unterstützt werden, nicht mehr transparent.

* https://www.netapp.com/data-storage/all-flash-san-storage-array/["Lesen Sie das ASA Datenblatt"^]
* Erfahren Sie mehr über das link:https://docs.netapp.com/us-en/asa-r2/learn-more/hardware-comparison.html["Neue ASA r2 Systeme im Vergleich zu den ASA Systemen"^]
* Den vollständigen Konfigurationsunterstützung und -Einschränkungen für ASA- und ASA r2-Systeme finden Sie in https://hwu.netapp.com/["NetApp Hardware Universe"^]




== FAS Hybrid-Flash-Systeme

FAS Hybrid-Flash-Systeme sind eine Hardwareplattform für gemeinsam genutzte, konsolidierte SAN- und NAS-Umgebungen, die ein umfassendes Datenmanagement und eine einfache Cloud-Anbindung erfordern.

Mit seiner hochverfügbaren Hardware erfüllen FAS Hybrid-Flash-Systeme die Workload-Anforderungen kostengünstig, indem sie die ideale Kombination aus Flash und herkömmlichen Festplatten kombinieren. Sie eignet sich ideal für Backup und Aufbewahrung, zur Konsolidierung allgemeiner Business-Applikationen und für verteilte Inhalte.

https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Lesen Sie das FAS Datenblatt"^]



== MetroCluster

Die Hardware-Storage-Systeme von ONTAP sind mit MetroCluster Funktionen von ONTAP konfiguriert und bieten eine Lösung, die ein Array-basiertes Clustering mit synchroner Replizierung kombiniert, um kontinuierliche Verfügbarkeit ohne Datenverluste zu gewährleisten. Die MetroCluster-Konfiguration dupliziert transaktionsorientiert sofort alle geschäftskritischen Daten und bietet einen unterbrechungsfreien Zugriff auf alle Applikationen und Daten.

Im Gegensatz zu herkömmlichen Lösungen zur Datenreplizierung arbeitet MetroCluster nahtlos mit Ihrer Host-Umgebung zusammen. Dadurch wird eine kontinuierliche Datenverfügbarkeit sichergestellt und Sie müssen sich nicht mit der Erstellung und Verwaltung komplizierter Failover-Skripts befassen.

https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["Erfahren Sie mehr über MetroCluster"^]



== ONTAP Software

Die ONTAP Datenmanagement-Software ist die Clustered Storage-Software, die die ONTAP Hardwaresysteme unterstützt. Mit einem Global Namespace, der bis zu 24 Hardware Nodes aller Art unterstützt, unterstützt die ONTAP Software Unified Storage (Block und Datei) und ermöglicht so eine beträchtliche Workload-Konsolidierung, die Sie über die ONTAP System Manager GUI managen können.

https://www.netapp.com/pdf.html?item=/media/7413-ds-3231.pdf["Lesen Sie das Datenblatt zur ONTAP Software"^]

.Finden Sie weitere Informationen
* https://docs.netapp.com/us-en/ontap-systems/index.html["ONTAP Hardwaresysteme – Dok"^]
* https://docs.netapp.com/us-en/ontap-metrocluster/index.html["MetroCluster Dokumentation"^]
* https://docs.netapp.com/us-en/ontap/index.html["ONTAP Dokumentation"^]

