---
settings:
  name: AFF and FAS Family
  search: ontap-systems,ontap-systems-upgrade,ontap-systems-switches,ontap-metrocluster
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Dokumentation zu ONTAP Hardwaresystemen
    url: "/index.html"
product-family:
  sidebarlinks:
  - title: Alle
    tags: tag_storage_management,tag_storage_upgrade,tag_storage_hardware,tag_get_started
    class: active
  - title: Los geht's
    tags: tag_get_started
  - title: Systemhardware
    tags: tag_storage_hardware
  - title: System-Upgrade
    tags: tag_storage_upgrade
  tiles:
  - title: Weitere Informationen zu ONTAP Hardware-Systemen
    icon: "./media/family.png"
    url: intro-family.html
    summary: Informieren Sie sich über die Hardwaresysteme von ONTAP.
    tags: all, tag_get_started
  - title: Installation und Wartung
    icon: "./media/icon-onprem.png"
    url: https://docs.netapp.com/us-en/ontap-systems/index.html
    summary: Installation und Wartung Ihrer ONTAP Hardwaresysteme.
    tags: all, tag_storage_hardware
  - title: Upgrade
    icon: "./media/upgrade.png"
    url: https://docs.netapp.com/us-en/ontap-systems-upgrade/index.html
    summary: Upgrade Ihrer ONTAP Hardwaresysteme.
    tags: all, tag_storage_upgrade
  - title: Cluster und Storage Switches
    icon: "./media/switch.png"
    url: https://docs.netapp.com/us-en/ontap-systems-switches/index.html
    summary: Installation, Upgrade und Wartung Ihrer Cluster- und Storage-Switches.
    tags: all, tag_storage_hardware, tag_storage_upgrade
  - title: ONTAP MetroCluster
    icon: "./media/metrocluster.png"
    url: https://docs.netapp.com/us-en/ontap-metrocluster/index.html
    summary: Installation und Upgrade oder Erweiterung Ihrer MetroCluster Konfigurationen
      für Disaster Recovery
    tags: all, tag_storage_upgrade
